info:
  component: Bulut Car Park

spring:
  application:
    name: bulut-carpark
  datasource:
    platform: mysql
    #    url: jdbc:mysql://localhost:3306/bulut_carpark?useSSL=false&storage_engine=InnoDB&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://bulutcarparkdb.cw2jrtacx03h.us-east-1.rds.amazonaws.com:3306/bulut_carpark?useSSL=false&storage_engine=InnoDB&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    #    username: root
    username: admin
    #    password: root
    password: yektan2019!
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 3000
      idle-timeout: 60000
      max-lifetime: 180000
      maximum-pool-size: 3
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  output:
    ansi:
      enabled: always
  jmx:
    enabled: false
  security:
    oauth2:
     resource:
      filter-order: 3
    basic:
     enabled: false
    signing-key: MaYzkSjmkzPC57L
    encoding-strength: 256
    security-realm: Bulut Car Park
    jwt:
      client-id: bulutcpjwtclientid
      client-secret: XY7kmzoNzl100
      grant-type: password
      scope-read: read
      scope-write: write
      resource-ids: bulutcpjwtresourceid
logging:
  level:
    # org.springframework: DEBUG
    org.springframework.web: DEBUG
  file: /jar/logs/application.log